### ISSUE TITLE
On Mobile device text typing speed become very slow 

### ISSUE THREAD

**Issue by rajivrisi** [alexmacarthur/typeit#51] opened 2017-11-09 13:02 UTC
On Mobile device text typing speed become very slow. First three events working fine. On 4th event works normal speed for first some characters. Later it takes nearly 2 seconds for each character. We tested this on android and iPhone. Both having same issue.

To reproduce the issue, add typing events to multiple element with some distance. First scroll top to bottom. You can see first some events will work normal. But others not. Now refresh page and scroll bottom to top, most of the events will not work with normal speed.

**Comment by gregdizzia** [comment] 2017-11-28 18:18
Seeing the same behavior with a type speed of 25.

You can view live on our site, https://bugplug.omatum.com -- Scroll down to the 'advanced intelligence' section and stare at the laptop screen - It will pop up a red window and show the slow (maybe around the 2s per character) speed. Looking for any sort of workaround.

**Comment by alexmacarthur** [comment] 2017-11-28 22:56
@gregdizzia, @rajivrisi Could you post how you're implementing TypeIt for those cases? Are you using the options object to define strings, or the companion functions? 

I can investigate why this is happening, I'd recommend checking out v5.0.0 in the meantime. It heavily rewrites TypeIt's core, and may have inadvertently solved this issue. Just note that there are breaking changes, most notably there's no more jQuery dependency.

**Comment by gregdizzia** [comment] 2017-11-29 01:17
@alexmacarthur Will Check out 5.0.0

Here's the code:

```
var $ta = $('#bugplug .form-step[data-step="submit-bug"] .textarea');

    $ta.addClass('focus');

    $ta.typeIt(
    {
      strings: "The subheaders aren't matching the current article. I'm guessing something broke in the association? Kinda critical.",
      speed: 25,
      callback: function(){setTimeout(function(){run_intel_anno()},500)}
});
```

**Comment by alexmacarthur** [comment] 2017-12-04 15:56
Have you had a chance to try this with v5.0.0+? I'm still unable to replicate locally. There may be some other scripts on the page colliding with it. 

My one other suspicion is that the instance is being recreated repeatedly. Is that snippet of code ever called more than once?

**Comment by alexmacarthur** [comment] 2018-01-02 23:42
Closing because of inability to replicate. Let me know if you see issues in the future.

**Comment by dave-sellers** [comment] 2018-02-22 09:26
I'm also experiencing this issue, using the following to instantiate:

```
animation = new TypeIt($text, {
	strings: strings,
	cursor: false,
	breakLines: false,
	loop: true,
	loopDelay: 5000,
	nextStringDelay: 2000
});
```

`strings` is an array of strings grabbed from a data-attribute. `$text` is a jQuery selected dom element.

While the characters are being 'typed', JS performance on the page drops significantly. Tested on a Galaxy S8 in Chrome.

**Comment by alexmacarthur** [comment] 2018-02-22 12:48
@dave-sellers Sorry about that -- do you happen to have a staging site you could show me? Is this only in development yet?

**Comment by dave-sellers** [comment] 2018-02-22 12:57
Hey, rather than putting a public link on here, is it okay to email you with more info?

**Comment by alexmacarthur** [comment] 2018-02-22 13:01
@dave-sellers You bet! alex@macarthur.me

**Comment by alexmacarthur** [comment] 2018-02-26 15:31
Issue was determined to probably be caused by running TypeIt in conjunction with another intensive JavaScript library on the page.

**Closed by alexmacarthur** 2018-02-26 15:31 UTC
